---
- hosts: appserver
  vars:
    control_server: swarnaravistar5.mylabserver.com
    web_root: /var/www/html/
  tasks:
  - name: Install Lynx on App servers
    yum: pkg=python state=installed update_cache=true
