--- # DNF MODULE EXAMPLE
- hosts: web
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Installing the apache module using DNF Update
      dnf: name="@Development tools" state=present
