--- # ERROR Handling Example
- hosts: apacheweb
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: Execute a command that fail fail
     command: /bin/false
     ignore_errors: yes
   - name: Install telnet
     yum: pkg=telnet state=latest
