--- # GET_URL MODULE EXAMPLE
- hosts: web
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Get and download the INI file from the web server
      get_url: url=http://swarnaravistar4.mylabserver.com/lookup.csv dest=/home/test/lookup.csv mode=0440
