--- # LOCAL ACTION DEMO
- hosts: apacheweb
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: Ping application aserver before we run our install
     local_action: command ping -c 4 swarnaravistar4
   - name: isntall git on remote server
     yum: pkg=git state=latest

