--- # MASTER INCLUD EXAMPLE
- hosts: apacheweb
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
   - include: plays/packages.yml
   - name: verify the telnet package installed
     raw: yum list installed | grep telnet > /home/test/pkgs.log

