--- # MOUNT MODULE EXAMPLE
- hosts: web
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: mount the remote data partition
      mount: name=/mnt/data src=/dev/xvdf1 fstype=ext3 opts=rw state=present
