--- # SEBOOLEAN MODULE EXAMPLE
- hosts: web
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Change Boolean for Anonymous Writes on the Web Server
      seboolean: name=httpd_anon_write state=no persistent=yes
