--- # SELINUX MODULE EXAMPLE
- hosts: web
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Change SELinux Configuration to Permissive
      selinux: policy=targeted state=permissive
