--- # TAGS FUNCTINALITY EXAMPLE
- hosts: apacheweb
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: install telnet and httpd
     yum: pkg={{item}} state=latest
     with_items:
      - telnet
      - httpd
     tags:
      - packages
   - name: Verfiy the telnet is installed
     raw: yum list installed | grep telnet > /home/test/pkg.log
     tags:
      - verification
