--- # UNTIL Playbook Exampl
- hosts: apacheweb
  user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: Installing the apache Web Server
     yum: pkg=httpd state=latest
   - name: Verify Service Status
     shell: systemctl status httpd
     register: result
     until: result.stdout.find("active (running)") != -1
     retries: 5
     delay: 5
   - debug: var=result
