- name: install apache webserver
  yum: pkg={{redhat_apache}} state=latest
  when: "ansible_os_family == 'RedHat'"
- name: Waite for the service to start listening 80
  wait_for:
    port: 80
    state: started
- debug: Need to install Git
  when: "ansible_os_family == 'RedHat'"
  notify: InstallGit
