- name: install the NFS server and utils
  yum: pkg={{item}} state=latest
  with_items:
   - "{{nfsutils_pkg}}"
   - "{{nfslibs_pkg}}"
- name: copy the export files to the remote server
  copy: src=exports.template dest=/etc/exports owner=root group=root mode=644
  notify:
   - StartServerService
