--- # File System Playbook
- hosts: databases
  user: test
  become: yes
  connection: ssh
  vars:
   distribution: RedHat
   nfsutils_pkg: nfs-utils
   nfslibs_pkg: nfs-utils-lib
   nfsserver_service: nfs-server
   nfslock_service: nfs-lock
   nfsmap_service: nfs-idmap
   rpcbind_service: rpcbind
   export_path: /var/share
   client_path: /mnt/remote
  tasks:
   - name: install the NFS server and utils
     yum: pkg={{item}} state=latest
     with_items:
      - "{{nfsutils_pkg}}"
      - "{{nfslibs_pkg}}"
   - name: copy the export files to the remote server
     copy: src=files/exports.template dest=/etc/exports owner=root group=root mode=644
     notify:
      - StartServerService
      - InstallClientPackages
      - CreateClientMount
      - clientMountServerResource
      - TestServerAvaialability
  handlers:
   - name: StartServerService
     service: name={{item}} state=restarted
     with_items:
      - "{{rpcbind_service}}"
      - "{{nfsserver_service}}"
      - "{{nfslock_service}}"
      - "{{nfsmap_service}}"
   - name: InstallClientPcakages
     yum: pkg={{item}} state=latest
     with_items:
      - "{{nfsutils_pkg}}"
      - "{{nfslibs_pkg}}"
     delegate_to: 127.0.0.1
     notify: StartClientService
   - name: StartClientService
     service: name={{item}} state=started
     with_items:
      - "{{rpcbind_service}}"
      - "{{nfslock_service}}"
      - "{{nfsmap_service}}"
     delegate_to: 127.0.0.1
   - name: CreateClientMount
     file: path={{client_path}} state=directory mode=755
     delegate_to: 127.0.0.1
   - name: ClientMountServerResource
     shell: mount -t nfs swarnaravistar3.mylabserver.com:{{export_path}} {{client_path}}
     register: result
     delegate_to: 127.0.0.1
   - name: TestServerAvailability
     debug: var=result 
