--- # Master Playbook Role based apache web deployment
- hosts: appserver
  user: test
  become: yes
  connection: ssh
  pre_tasks:
  - name: How long the role module took to run
    raw: date > /home/test/startorole.log
  roles:
    - redhat.apachewebserver
  post_tasks:
  - name: when did the role end
    raw: date > /home/test/endrole.log
