--- # Master Webserve Playbook
- hosts: '{{hosts}}'
  user: '{{user}}'
  become: yes
  connection: ssh
  pre_tasks:
  - name: How long the role module took to run
    raw: date > /home/test/startorole.log
  roles:
    - { role: '{{role}}', when: "ansible_os_family == 'RedHat'" }
  post_tasks:
  - name: when did the role end
    raw: date > /home/test/endrole.log
