- name: InstallClientPcakages
  yum: pkg={{item}} state=latest
  with_items:
  - "{{nfsutils_pkg}}"
  - "{{nfslibs_pkg}}"
  notify: StartClientService
- name: StartClientService
  service: name={{item}} state=started
  with_items:
  - "{{rpcbind_service}}"
  - "{{nfslock_service}}"
  - "{{nfsmap_service}}"
- name: CreateClientMount
  file: path={{client_path}} state=directory mode=755
- name: ClientMountServerResource
  shell: mount -t nfs swarnaravistar5.mylabserver.com:{{export_path}} {{client_path}}
  register: result
