- name: copy the export files to the remote server
  copy: src=exports.template dest=/etc/exports owner=root group=root mode=644
  notify:
   - InstallClientPackages
   - CreateClientMount
   - clientMountServerResource
   - TestServerAvaialability
